Read only queries
geniusproject/nefertari-sqla pull request #63
Opened 2017-05-30 12:54 UTC by nikitagromov

2017-05-30 18:02 UTC, nmenardg requested changes

2017-05-30 18:02 UTC, nmenardg commented on nefertari_sqla/documents.py
> +        raise NoResultFound('There is no results according to passed params')
This is not if there's no result, it's if no params were given.

2017-05-30 18:02 UTC, nmenardg commented on nefertari_sqla/documents.py
> +        inst = inspect(cls)
What's `inst`?

2017-05-30 18:02 UTC, nmenardg commented on nefertari_sqla/documents.py
> +            single_value, *_ = packed_value
Wouldn't `single_value = next(gen, None)` do the same thing?

2017-05-30 18:02 UTC, nmenardg commented on nefertari_sqla/documents.py
> +            query = cls.session_factory().query(cls).from_statement(statement)
Wouldn't this work?
```python
cls.session_factory().query(cls)
```

2017-05-30 18:58 UTC, nikitagromov commented on nefertari_sqla/documents.py
> +            query = cls.session_factory().query(cls).from_statement(statement)
@nmenardg you mean without `from_statement` ?

2017-05-30 18:59 UTC, nikitagromov commented on nefertari_sqla/documents.py
> +        raise NoResultFound('There is no results according to passed params')
@nmenardg what do you think which kind of exception we should raise here ?

2017-06-12 16:08 UTC, nmenardg approved these changes

2017-06-15 18:54 UTC, merged